name: Docker Build Trigger

on:
  push:
    branches: [ main ]

jobs:
  call-docker-workflow:
    uses: owner/repo1/.github/workflows/docker-build-push.yml@main
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_ACCESS_TOKEN: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
